apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webecho
  name: webecho
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webecho
  template:
    metadata:
      labels:
        app: webecho
    spec:
      containers:
      - name: webecho
        image: lijie0123/webecho:slim
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 1
            memory: 128Mi
          requests:
            cpu: 1
            memory: 128Mi
        readinessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            periodSeconds: 300
            successThreshold: 1
            failureThreshold: 6
            timeoutSeconds: 1
        livenessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            periodSeconds: 600
            successThreshold: 1
            failureThreshold: 24
            timeoutSeconds: 1
        startupProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            periodSeconds: 1
            failureThreshold: 10
            timeoutSeconds: 1
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: webecho
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: webecho
